# Application: Scout Engineering Day
# Author: Walter Hiranpat
# Ansible tasks playbook

---
- name: Load vars
  include_vars: 
    file: "vars/{{ansible_local.common.environment}}.vault.yml"

- name: Install yum package
  yum:
    pkg: "{{ item }}"
  with_items:
    - nano
    - curl
    - git
    - python-pip
    - python-psycopg2
    - python-setuptools
    - mysql
  become: true

- name: Install docker-py
  pip:
    name: docker-py
  become: true

- name: Install docker
  yum:
    name: docker
    state: latest
  become: true

- name: Ensure docker deamon is running
  service:
    name: docker
    state: started
    enabled: yes
  become: true

#------Setup Application-------#
- name: Git clone SED-Documentations
  git:
    repo: https://github.com/{{documentation.githubOwner}}/SED-Documentations.git
    dest: /ansible/SED-Documentations
    accept_hostkey: true
    version: "{{documentation.githubBranch}}"
    update: no

#------Setup Application-------#
- name: Git clone SED-Database-test
  git:
    repo: https://github.com/{{database.githubOwner}}/SED-Database-Test.git
    dest: /ansible/SED-Database-Test
    accept_hostkey: true
    version: "{{database.githubBranch}}"
    update: no

- name: start the mysql container
  docker_container:
    image: mysql:latest
    name: sed_database
    restart_policy: always
    ports:
    - 3306:3306
    env:
      MYSQL_DATABASE: SED_Database
      MYSQL_USER: sed_admin
      MYSQL_PASSWORD: "{{secrets.database.user.password}}"
      MYSQL_ROOT_PASSWORD: "{{secrets.database.root.password}}"
  become: true

#------Setup Application-------#
- name: Git clone SED-Web-Applications
  git:
    repo: https://github.com/{{website.githubOwner}}/SED-Web-Application.git
    dest: /ansible/SED-Web-Application
    accept_hostkey: true
    version: "{{website.githubBranch}}"
    update: no

- name: Set allowed hosts
  lineinfile:
    path: /ansible/SED-Web-Application/SED/settings.py
    regexp: "ALLOWED_HOSTS\\s*="
    line: "ALLOWED_HOSTS = ['{{ host | default('localhost') }}']"

- name: Replace database settings - User password
  replace:
    path: /ansible/SED-Web-Application/SED/database_settings.py
    regexp: "('PASSWORD':\\s*)'.*'"
    replace: "\\1'{{secrets.database.user.password}}'"

- name: Replace database settings - root password
  replace:
    path: /ansible/SED-Web-Application/SED/database_settings.py
    regexp: "('MYSQL_PASSWORD':\\s*)'.*'"
    replace: "\\1'{{secrets.database.root.password}}'"

- name: create sed image
  docker_image:
    name: sed_image
    tag: latest
    path: /ansible/SED-Web-Application/
    state: build
  become: true

- name: Start SED-Web-Application Container
  docker_container:
    image: sed_image:latest
    name: sed_website
    restart_policy: always
    ports:
    - 8000:8000
    links:
    - "sed_database"
  become: true

- name: Enable execution of script to populate test data
  file:
    path: /ansible/PopulateTestData.sh
    mode: 0544

- name: Wait for port 3306
  wait_for:
    host: 172.17.0.2
    port: 3306

- name: Run SQL scripts to populate the database with test data
  command: /ansible/PopulateTestData.sh /ansible/SED-Database-Test/{{database.scriptPath}} {{secrets.database.root.password}} sed_database

#------Setup Presentation: Introduction-------#
- name: Create Kick Off Presentation Image
  docker_image:
    name: sed_kick_off
    tag: latest
    path: /ansible/SED-Documentations/presentations/SED-Presentation1-Kick-Off/
    state: build
  become: true

- name: Start Kick Off Presentation Container
  docker_container:
    image: sed_kick_off:latest
    name: sed_kickoff
    ports:
    - 9000:8000

  become: true

#------Setup Presentation: Technologies------#
- name: Create Technology Environment Presentation Image
  docker_image:
    name: sed_tech
    tag: latest
    path: /ansible/SED-Documentations/presentations/SED-Presentation2-Technologies/
    state: build
  become: true

- name: Start Technologies Environment Presentation Container
  docker_container:
    image: sed_tech:latest
    name: sed_tech
    ports:
    - 9001:8000
  become: true

#------Setup Presentation: Application-------#
- name: Create Training Presentation Image
  docker_image:
    name: sed_training
    tag: latest
    path: /ansible/SED-Documentations/presentations/SED-Presentation3-Training/
    state: build
  become: true

- name: Start Training Presentation Container
  docker_container:
    image: sed_training:latest
    name: sed_training
    ports:
    - 9002:8000
  become: true

#------Setup Presentation: Training-------#
- name: Create Overview Presentation Image
  docker_image:
    name: sed_overview
    tag: latest
    path: /ansible/SED-Documentations/presentations/SED-Presentation4-Overview/
    state: build
  become: true

- name: Start Overview Presentation Container
  docker_container:
    image: sed_overview:latest
    name: sed_overview
    ports:
    - 9003:8000
  become: true

#------chmod +x ./SED-doc-update.sh------#
- name: Set permissions to sed-doc-update.sh
  file: 
    dest: /ansible/SED-doc-update.sh 
    mode: a+x
  become: true

- name: set permissions to SED-web-update.sh
  file: 
    dest: /ansible/SED-web-update.sh 
    mode: a+x
  become: true
