---
website:
  githubOwner: ScoutEngineeringDay
  githubBranch: master
database:
  githubOwner: ScoutEngineeringDay
  githubBranch: master
  scriptPath: SED_RDB
documentation:
  githubOwner: ScoutEngineeringDay
  githubBranch: master
