# Application: Scout Engineering Day
# Author: Walter Hiranpat
# Ansible tasks playbook

---
- name: Install yum package
  yum:
    pkg: "{{ item }}"
  with_items:
    - nano
    - curl
    - git
    - python-pip
    - python-psycopg2
    - python-setuptools
    - mysql
  become: true

- name: Install virtualenv
  pip:
    name: virtualenv
  become: true

- name: Install docker-py
  pip:
    name: docker-py
  become: true

- name: Install docker
  yum:
    name: docker
    state: latest
  become: true

- name: Ensure docker deamon is running
  service:
    name: docker
    state: started
  become: true

#------Setup Application-------#
- name: create docker consul
  docker_container:
    image: consul:latest
    name: consul
  become: true

#------Setup Application-------#
- name: create docker vault
  docker_container:
    image: vault:latest
    name: vault
  become: true

#------Setup Application-------#
- name: check SED-db 
  stat:
    path: /vagrant/SED-Documentations
  register: doc_result

- name: Git clone SED-Documentations
  git:
    repo: https://github.com/{{documentation.githubOwner}}/SED-Documentations.git
    dest: /vagrant/SED-Documentations
    accept_hostkey: true
    update: true
    version: "{{documentation.githubBranch}}"
  when: doc_result.stat.exists == False

#------Setup Application-------#
- name: check SED-db 
  stat:
    path: /vagrant/SED-Database-Test
  register: db_result

- name: Git clone SED-Database-test
  git:
    repo: https://github.com/{{database.githubOwner}}/SED-Database-Test.git
    dest: /vagrant/SED-Database-Test
    accept_hostkey: true
    update: true
    version: "{{database.githubBranch}}"
  when: db_result.stat.exists == False

- name: start the mysql container
  docker_container:
    image: mysql:latest
    name: sed_database
    ports:
    - 3306:3306
    env:
      MYSQL_DATABASE: SED_Database
      MYSQL_USER: sed_admin
      MYSQL_PASSWORD: sed_password
      MYSQL_ROOT_PASSWORD: sed_password
  become: true

- name: Enable execution of script to populate test data
  file:
    path: /vagrant/PopulateTestData.sh
    mode: 0544

- name: Wait for port 3306
  wait_for:
    host: 172.17.0.4
    port: 3306

- name: Run SQL scripts to populate the database with test data
  command: /vagrant/PopulateTestData.sh /vagrant/SED-Database-Test/{{database.scriptPath}} sed_password sed_database

#------Setup Application-------#
- name: check SED-web
  stat:
    path: /vagrant/SED-Web-Application
  register: web_result

- name: Git clone SED-Web-Applications
  git:
    repo: https://github.com/{{website.githubOwner}}/SED-Web-Application.git
    dest: /vagrant/SED-Web-Application
    accept_hostkey: true
    update: true
    version: "{{website.githubBranch}}"
  when: web_result.stat.exists == False

- name: create sed image
  docker_image:
    name: sed_image
    tag: latest
    path: /vagrant/SED-Web-Application/
    state: build
  become: true

- name: Start SED-Web-Application Container
  docker_container:
    image: sed_image:latest
    name: sed_website
    ports:
    - 8000:8000
    links:
    - "sed_database"
  become: true

# #------Setup Presentation: Introduction-------#
# - name: Create Kick Off Presentation Image
#   docker_image:
#     name: sed_kick_off
#     tag: latest
#     path: /vagrant/SED-Documentations/presentations/SED-Presentation1-Kick-Off/
#     state: build
#   become: true

# - name: Start Kick Off Presentation Container
#   docker_container:
#     image: sed_kick_off:latest
#     name: sed_kickoff
#     ports:
#     - 9000:8000

#   become: true

# #------Setup Presentation: Technologies------#
# - name: Create Technology Environment Presentation Image
#   docker_image:
#     name: sed_tech
#     tag: latest
#     path: /vagrant/SED-Documentations/presentations/SED-Presentation2-Technologies/
#     state: build
#   become: true

# - name: Start Technologies Environment Presentation Container
#   docker_container:
#     image: sed_tech:latest
#     name: sed_tech
#     ports:
#     - 9001:8001
#   become: true

# #------Setup Presentation: Application-------#
# - name: Create Training Presentation Image
#   docker_image:
#     name: sed_training
#     tag: latest
#     path: /vagrant/SED-Documentations/presentations/SED-Presentation3-Training/
#     state: build
#   become: true

# - name: Start Training Presentation Container
#   docker_container:
#     image: sed_training:latest
#     name: sed_training
#     ports:
#     - 9002:8002
#   become: true

# #------Setup Presentation: Training-------#
# - name: Create Overview Presentation Image
#   docker_image:
#     name: sed_overview
#     tag: latest
#     path: /vagrant/SED-Documentations/presentations/SED-Presentation4-Overview/
#     state: build
#   become: true

# - name: Start Overview Presentation Container
#   docker_container:
#     image: sed_overview:latest
#     name: sed_overview
#     ports:
#     - 9003:8003
#   become: true