# Application: Scout Engineering Day
# Author: Walter Hiranpat
# Ansible tasks playbook

---
- name: Install yum package
  yum:
    pkg: "{{ item }}"
  with_items:
    - nano
    - curl
    - git
    - python-pip
    - python-psycopg2
    - python-setuptools
  sudo: true

- name: Install virtualenv
  pip:
    name: virtualenv
  sudo: true

- name: Install docker-py
  pip:
    name: docker-py
  sudo: true

- name: Install docker
  yum:
    name: docker
    state: latest
  sudo: true

- name: Ensure docker deamon is running
  service:
    name: docker
    state: started
  become: true

#------Setup Application-------#
- name: create docker consul
  docker:
    image: consul:latest
    name: consul
  sudo: true

#------Setup Application-------#
- name: create docker vault
  docker:
    image: vault:latest
    name: vault
  sudo: true

#------Setup Application-------#
- name: Git clone SED-Documentations
  git:
    repo: https://github.com/ScoutEngineeringDay/SED-Documentations.git
    dest: /home/vagrant/SED-Doc
    accept_hostkey: true
    update: true

#------Setup Application-------#
- name: Git clone SED-Database-test
  git:
    repo: https://github.com/ScoutEngineeringDay/SED-Database-Test.git
    dest: /home/vagrant/SED-Db-scripts
    accept_hostkey: true
    update: true

- name: start the mysql container
  docker:
    image: mysql:latest
    name: sed_database
    publish_all_ports: true
    env:
      MYSQL_DATABASE: sed_database
      MYSQL_USER: sed_admin
      MYSQL_ROOT_PASSWORD: sed_password
  sudo: true

#------Setup Application-------#
- name: Git clone SED-Web-Applications
  git:
    repo: https://github.com/ScoutEngineeringDay/SED-Web-Application.git
    dest: /home/vagrant/SED-Web
    accept_hostkey: true
    update: true

- name: create sed image
  docker_image:
    name: sed_image
    tag: latest
    path: /home/vagrant/SED-Web/
    state: build
  sudo: true

- name: Start SED-Web-Application Container
  docker:
    image: sed_image:latest
    name: sed_website
    publish_all_ports: true
    links:
    - "sed_database"
  sudo: true


#------Setup Presentation: Introduction-------#
- name: Create Kick Off Presentation Image
  docker_image:
    name: sed_kick_off
    tag: latest
    path: /home/vagrant/SED-Doc/presentations/SED-Presentation1-Kick-Off/
    state: build
  sudo: true

- name: Start Kick Off Presentation Container
  docker:
    image: sed_kick_off:latest
    name: sed_kickoff
    publish_all_ports: true
    ports:
      "9000:8000"
  sudo: true
#------Setup Presentation: Database-------#

#------Setup Presentation: DevOps-------#

#------Setup Presentation: Application-------#

#------Setup Presentation: Training-------#

#------Setup Presentation: Final-------#
