# Application: Scout Engineering Day
# Author: Walter Hiranpat
# Ansible tasks playbook

---
- name: Install yum package
  yum:
    pkg: "{{ item }}"
  with_items:
    - nano
    - curl
    - git
    - python-pip
    - python-psycopg2
    - python-setuptools
    - mysql
  become: true

- name: Install virtualenv
  pip:
    name: virtualenv
  become: true

- name: Install docker-py
  pip:
    name: docker-py
  become: true

- name: Install docker
  yum:
    name: docker
    state: latest
  become: true

- name: Ensure docker deamon is running
  service:
    name: docker
    state: started
  become: true

#------Setup Application-------#
- name: create docker consul
  docker_container:
    image: consul:latest
    name: consul
  become: true

#------Setup Application-------#
- name: create docker vault
  docker_container:
    image: vault:latest
    name: vault
  become: true

#------Setup Application-------#
- name: Git clone SED-Documentations
  git:
    repo: https://github.com/{{documentation.githubOwner}}/SED-Documentations.git
    dest: /home/vagrant/SED-Doc
    accept_hostkey: true
    update: true
    version: "{{documentation.githubBranch}}"

#------Setup Application-------#
- name: Git clone SED-Database-test
  git:
    repo: https://github.com/{{database.githubOwner}}/SED-Database-Test.git
    dest: /home/vagrant/SED-Db-scripts
    accept_hostkey: true
    update: true
    version: "{{database.githubBranch}}"

- name: start the mysql container
  docker_container:
    image: mysql:latest
    name: sed_database
    ports:
    - 3306:3306
    env:
      MYSQL_DATABASE: SED_Database
      MYSQL_USER: sed_admin
      MYSQL_PASSWORD: sed_password
      MYSQL_ROOT_PASSWORD: sed_password
  become: true

- name: Enable execution of script to populate test data
  file:
    path: /vagrant/PopulateTestData.sh
    mode: 0544

- name: Wait for port 3306
  wait_for:
    host: 172.17.0.4
    port: 3306

- name: Run SQL scripts to populate the database with test data
  command: /vagrant/PopulateTestData.sh /home/vagrant/SED-Db-scripts/{{database.scriptPath}} sed_password sed_database

#------Setup Application-------#
- name: Git clone SED-Web-Applications
  git:
    repo: https://github.com/{{website.githubOwner}}/SED-Web-Application.git
    dest: /home/vagrant/SED-Web
    accept_hostkey: true
    update: true
    version: "{{website.githubBranch}}"

- name: create sed image
  docker_image:
    name: sed_image
    tag: latest
    path: /home/vagrant/SED-Web/
    state: build
  become: true

- name: Start SED-Web-Application Container
  docker_container:
    image: sed_image:latest
    name: sed_website
    ports:
    - 8000:8000
    links:
    - "sed_database"
  become: true

#------Setup Presentation: Introduction-------#
- name: Create Kick Off Presentation Image
  docker_image:
    name: sed_kick_off
    tag: latest
    path: /home/vagrant/SED-Doc/presentations/SED-Presentation1-Kick-Off/
    state: build
  become: true

- name: Start Kick Off Presentation Container
  docker_container:
    image: sed_kick_off:latest
    name: sed_kickoff
    ports:
    - 9000:8000
  become: true
#------Setup Presentation: Database-------#

#------Setup Presentation: DevOps-------#

#------Setup Presentation: Application-------#

#------Setup Presentation: Training-------#

#------Setup Presentation: Final-------#
