# Application: Scout Engineering Day
# Author: Walter Hiranpat
# Ansible tasks playbook

---
- name: Install yum package
  yum:
    pkg: "{{ item }}"
  with_items:
    - nano
    - curl
    - git
    - python-pip
    - python-psycopg2
    - python-setuptools
  sudo: true

- name: Install virtualenv
  pip:
    name: virtualenv
  sudo: true

- name: Install docker-py
  pip:
    name: docker-py
  sudo: true

- name: Install docker
  yum:
    name: docker
    state: latest
  sudo: true

- name: Ensure docker deamon is running
  service:
    name: docker
    state: started
  become: true

#------Setup Application-------#
- name: create docker consul
  docker:
    image: consul:latest
    name: consul
  sudo: true

#------Setup Application-------#
- name: create docker vault
  docker:
    image: vault:latest
    name: vault
  sudo: true

#------Setup Application-------#
- name: Git clone SED-Documentations
  git:
    repo: https://github.com/ScoutEngineeringDay/SED-Documentations.git
    dest: /home/vagrant/SED-Doc
    update: true

#------Setup Application-------#
- name: Git clone SED-Database-test
  git:
    repo: https://github.com/ScoutEngineeringDay/SED-Database-Test.git
    dest: /home/vagrant/SED-Db-scripts
    update: true

- name: start the mysql container
  docker:
    image: mysql:latest
    name: mysql_DB
    publish_all_ports: True
    env:
      MYSQL_USER: sed_admin
      MYSQL_ROOT_PASSWORD: sed_password
  sudo: true

#------Setup Application-------#
- name: Git clone SED-Web-Applications
  git:
    repo: https://github.com/ScoutEngineeringDay/SED-Web-Application.git
    dest: /home/vagrant/SED-Web
    update: true

# - name: Start SED-Web-Application Container
#   docker:
#     image

#------Setup Presentation: Introduction-------#
# - name: Introduction presentation
#   docker:
#     image: nbrown/revealjs
#     name: IntroductionPresentation
#     ports: 
#     - 8000:9000
#     volumes:
#     - /home/vagrant/SED-Doc/presentation1/index.html:reveal.js/index.html
#     - /home/vagrant/SED-Doc/presentation1/media:/reveal.js/media
#     - /home/vagrant/SED-Doc/presentation1/css:/reveal.js/css
#     - /home/vagrant/SED-Doc/plugin:/reveal.js/css
#     - /home/vagrant/SED-Doc/presentation1/md:/reveal.js/md

#------Setup Presentation: Database-------#

#------Setup Presentation: DevOps-------#

#------Setup Presentation: Application-------#

#------Setup Presentation: Training-------#

#------Setup Presentation: Final-------#
